# Generated by Django 4.2 on 2024-08-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_passwordreset'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_email_notifications_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='excercise_time',
            field=models.CharField(choices=[('30_minutes', '30 Minutes')], default='30_minutes', max_length=100),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='goal',
            field=models.CharField(choices=[('general_health_monitoring', 'General Health Monitoring'), ('health_information_storage', 'Health Information Storage'), ('chronic_condition_monitoring', 'Chronic Condition Monitoring'), ('preventive_health_management', 'Preventive Health Management'), ('diagonistic_test_recommendations', 'Diagonistic Test Recommendations')], default='general_health_monitoring', max_length=250),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='height',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='insurance_company_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='insurance_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='sponsor_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='weight',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='zip_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
