# Generated by Django 4.2 on 2024-08-27 09:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_stripe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activation_token',
            field=models.CharField(
                blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='activation_token_created_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(
                message='Enter a valid phone number in the format: +91XXXXXXXXXX', regex='^\\+1?\\d{1,8}\\d{4,20}$')]),
        ),
    ]
