# Generated by Django 4.2 on 2024-09-02 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_userloginactivity_alter_user_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
