# Generated by Django 4.2 on 2024-09-09 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_delete_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transactions',
        ),
    ]
