# Generated by Django 4.2 on 2024-09-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_delete_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('female_to_male', 'Female-to-Male'), ('male_to_female', 'Male-to-Female')], default='male', max_length=15),
        ),
    ]
