# Generated by Django 4.2 on 2024-09-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_personalinfo_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscriptions',
            name='status',
            field=models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('cancelled', 'Cancelled')], default='trial', max_length=10),
        ),
    ]
