# Generated by Django 4.2 on 2024-09-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_usersubscriptions_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscriptions',
            name='status',
            field=models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='trial', max_length=10),
        ),
    ]
