# Generated by Django 4.2 on 2024-09-19 12:08

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='excercise_activities',
            field=models.JSONField(blank=True, null=True, validators=[user.models.validate_exercise]),
        ),
    ]
