# Generated by Django 4.2 on 2024-09-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_personalinfo_excercise_activities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='excercise_time',
            field=models.CharField(choices=[('15_minutes', '15 Minutes'), ('30_minutes', '30 Minutes'), ('45_minutes', '45 Minutes'), ('1_hour', '1 Hour'), ('more_than_1_hour', 'More than 1 Hour')], default='30_minutes', max_length=100),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='exercise_frequency',
            field=models.CharField(choices=[('1-3_times_per_week', '1-3 times per week'), ('4-5_times_per_week', '4-5 times per week'), ('6-7_times_per_week', '6-7 times per week'), ('occasionally', 'Occasionally'), ('never', 'Never')], default='NEVER', max_length=20),
        ),
    ]
