# Generated by Django 4.2 on 2024-09-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_alter_personalinfo_goal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalinfo',
            old_name='height',
            new_name='feet',
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='inches',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
