# Generated by Django 4.2 on 2024-09-24 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_rename_height_personalinfo_feet_personalinfo_inches'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='current_health',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('female_to_male', 'Female-to-Male'), ('male_to_female', 'Male-to-Female')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='intensity_of_excercise',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('female_to_male', 'Female-to-Male'), ('male_to_female', 'Male-to-Female')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='symptom',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('female_to_male', 'Female-to-Male'), ('male_to_female', 'Male-to-Female')], max_length=100, null=True),
        ),
    ]
