# Generated by Django 4.2 on 2024-09-25 12:54

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_alter_personalinfo_excercise_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.dynamic_upload_path),
        ),
    ]
