# Generated by Django 4.2 on 2024-10-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_alter_personalinfo_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='file_name',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
