# Generated by Django 4.2 on 2024-10-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_personalinfo_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='is_smoker',
            field=models.BooleanField(default=None),
        ),
    ]
