# Generated by Django 4.2 on 2024-10-16 10:44

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_alter_personalinfo_is_smoker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=user.models.dynamic_upload_path),
        ),
    ]
