from django.db import models

class CPTData(models.Model):
    provider_id = models.CharField(max_length=50, primary_key=True)
    provider_id_npi = models.DecimalField(max_digits=15, decimal_places=0)
    provider_name = models.CharField(max_length=255)
    provider_type = models.CharField(max_length=50)
    procedure_id = models.CharField(max_length=50)
    procedure_description = models.TextField()
    procedure_num_patient_bills = models.DecimalField(max_digits=10, decimal_places=2)
    provider_rate = models.DecimalField(max_digits=15, decimal_places=2)
    area_market_rate = models.DecimalField(max_digits=15, decimal_places=2)
    rate_percent_difference = models.DecimalField(max_digits=10, decimal_places=2)
    area_min_procedure_rate = models.DecimalField(max_digits=15, decimal_places=2)
    area_max_procedure_rate = models.DecimalField(max_digits=15, decimal_places=2)
    area_mile_radius = models.IntegerField()
    area_num_providers = models.DecimalField(max_digits=10, decimal_places=2)
    provider_specialty = models.CharField(max_length=255)
    group_provider_specialty = models.CharField(max_length=255)
    secondary_specialties = models.TextField()
    street_address = models.CharField(max_length=255)
    full_address = models.TextField()
    zip_code = models.CharField(max_length=20)
    # zip_code_old = models.CharField(max_length=20)
    phone_number = models.CharField(max_length=20)
    latitude = models.DecimalField(max_digits=10, decimal_places=6)
    longitude = models.DecimalField(max_digits=10, decimal_places=6)
    google_maps_link = models.TextField()
    hospital_ownership = models.CharField(max_length=50)
    offers_emergency_services = models.CharField(max_length=10)
    num_group_members = models.DecimalField(max_digits=10, decimal_places=2)
    credentials = models.CharField(max_length=255)
    medical_school = models.CharField(max_length=255)
    graduation_year = models.DecimalField(max_digits=4, decimal_places=0)
    associated_organizations = models.TextField()
    associated_hospitals = models.TextField()
    state = models.CharField(max_length=10)
    city = models.CharField(max_length=10)

    class Meta:
        db_table = 'cpt_data'
