# Generated by Django 4.2 on 2024-08-26 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userservicetoken',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
