# Generated by Django 4.2 on 2024-08-28 10:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_userservicetoken_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='reference',
            field=models.CharField(default=django.utils.timezone.now, max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userservicetoken',
            name='access_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userservicetoken',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
