# Generated by Django 4.2 on 2024-09-02 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_provider_reference_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='service',
            name='client_secret',
        ),
    ]
