# Generated by Django 4.2 on 2024-09-04 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0005_condition_ref_num_encounter_ref_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='date_of_record',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='record_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
