# Generated by Django 4.2 on 2024-09-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0006_alter_encounter_date_of_record_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encounter',
            name='condition',
        ),
        migrations.AddField(
            model_name='condition',
            name='record_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
