# Generated by Django 4.2 on 2024-09-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0007_remove_encounter_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='health_indicator',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
