# Generated by Django 4.2 on 2024-09-10 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0008_alter_condition_health_indicator'),
    ]

    operations = [
        migrations.CreateModel(
            name='InitialDataSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(choices=[('encounter', 'encounter'), ('condition', 'condition'), ('prescription', 'prescription'), ('document', 'document'), ('careplan', 'careplan'), ('allergyintolerence', 'allergyintolerence')], max_length=100)),
                ('user_service_id', models.CharField(max_length=150)),
                ('user', models.CharField(max_length=150)),
                ('task_id', models.CharField(max_length=150)),
                ('is_complete', models.BooleanField(default=False)),
                ('error_msg', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchedulerDataSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(choices=[('encounter', 'encounter'), ('condition', 'condition'), ('prescription', 'prescription'), ('document', 'document'), ('careplan', 'careplan'), ('allergyintolerence', 'allergyintolerence')], max_length=100)),
                ('user_service_id', models.CharField(max_length=150)),
                ('user', models.CharField(max_length=150)),
                ('task_id', models.CharField(max_length=150)),
                ('is_complete', models.BooleanField(default=False)),
                ('error_msg', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
