# Generated by Django 4.2 on 2024-09-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0011_immunization_allergy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergy',
            name='file',
            field=models.FileField(upload_to='allergy/'),
        ),
        migrations.AlterField(
            model_name='immunization',
            name='file',
            field=models.FileField(upload_to='immunization/'),
        ),
    ]
