# Generated by Django 4.2 on 2024-09-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0012_alter_allergy_file_alter_immunization_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='files',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('blood_results', 'Blood Results'), ('x_rays', 'X-Rays'), ('imaging', 'Imaging'), ('lab_tests', 'Lab Tests'), ('vaccines', 'Vaccines'), ('fertility', 'Fertility'), ('genetics', 'Genetics'), ('others', 'Others')], default='blood_results'),
        ),
        migrations.DeleteModel(
            name='DocumentDetail',
        ),
    ]
