# Generated by Django 4.2 on 2024-09-24 10:48

from django.db import migrations, models
import health.models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0014_datasynclog_delete_initialdatasynclog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergy',
            name='file',
            field=models.FileField(upload_to=health.models.dynamic_upload_path),
        ),
        migrations.AlterField(
            model_name='immunization',
            name='file',
            field=models.FileField(upload_to=health.models.dynamic_upload_path),
        ),
    ]
