# Generated by Django 4.2 on 2024-09-25 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0015_alter_allergy_file_alter_immunization_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('blood_results', 'Blood Results'), ('x_rays', 'X-Rays'), ('imaging', 'Imaging'), ('lab_tests', 'Lab Tests'), ('vaccines', 'Vaccines'), ('fertility', 'Fertility'), ('genetics', 'Genetics'), ('others', 'Others'), ('synchronized', 'Synchronized Documents')], default='synchronized'),
        ),
    ]
