# Generated by Django 4.2 on 2024-09-25 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0016_alter_document_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familymember',
            name='user',
        ),
        migrations.DeleteModel(
            name='FamilyMedicalHistory',
        ),
        migrations.DeleteModel(
            name='FamilyMember',
        ),
    ]
