# Generated by Django 4.2 on 2024-09-25 06:19

from django.db import migrations, models
import health.models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0017_remove_familymember_user_delete_familymedicalhistory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='files',
            field=models.FileField(null=True, upload_to=health.models.dynamic_upload_path),
        ),
    ]
