# Generated by Django 4.2 on 2024-10-07 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0020_celerytaskmeta_datasynclog_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasynclog',
            old_name='is_initial_sync',
            new_name='initial_sync',
        ),
        migrations.RenameField(
            model_name='userservicetoken',
            old_name='is_initial_sync',
            new_name='initial_sync',
        ),
    ]
