# Generated by Django 4.2 on 2024-10-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0021_rename_is_initial_sync_datasynclog_initial_sync_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSyncExceptionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=150)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='file_name',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
