# Generated by Django 4.2 on 2024-10-10 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0022_datasyncexceptionlog_document_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasynclog',
            name='payload',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
