# Generated by Django 4.2 on 2024-10-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0023_datasynclog_payload'),
    ]

    operations = [
        migrations.AddField(
            model_name='allergy',
            name='file_name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='immunization',
            name='file_name',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
