# Generated by Django 4.2 on 2024-10-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0024_allergy_file_name_immunization_file_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasynclog',
            old_name='completed_count',
            new_name='completed_page_count',
        ),
        migrations.RenameField(
            model_name='datasynclog',
            old_name='initial_sync',
            new_name='is_initial_sync',
        ),
        migrations.RenameField(
            model_name='datasynclog',
            old_name='total_count',
            new_name='total_page_count',
        ),
        migrations.AddField(
            model_name='datasynclog',
            name='sync_type',
            field=models.CharField(choices=[('initial', 'initial'), ('refresh', 'refresh')], default='initial', max_length=100),
        ),
        migrations.AddField(
            model_name='userservicetoken',
            name='ongoing_sync_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userservicetoken',
            name='sync_status',
            field=models.CharField(choices=[('processing', 'processing'), ('completed', 'completed')], default='processing', max_length=100),
        ),
    ]
