# Generated by Django 4.2 on 2024-10-22 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0025_rename_completed_count_datasynclog_completed_page_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasynclog',
            name='is_initial_sync',
        ),
    ]
