# Generated by Django 4.2 on 2024-10-15 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0026_remove_datasynclog_is_initial_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='condition',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
