# Generated by Django 4.2 on 2024-10-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0027_encounter_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userservicetoken',
            name='sync_status',
            field=models.CharField(choices=[('processing', 'processing'), ('completed', 'completed'), ('failed', 'failed')], default='processing', max_length=100),
        ),
    ]
