# Generated by Django 4.2 on 2024-11-25 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('health', '0028_alter_userservicetoken_sync_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalAPILog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('api_endpoint', models.TextField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('is_sucess_response', models.BooleanField(default=True)),
                ('error_message', models.JSONField(blank=True, null=True)),
                ('is_initial_sync', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_api_log', to=settings.AUTH_USER_MODEL)),
                ('user_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_api_log', to='health.userservicetoken')),
            ],
        ),
    ]
