# Generated by Django 4.2 on 2024-11-25 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0029_externalapilog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='externalapilog',
            old_name='is_sucess_response',
            new_name='is_success_response',
        ),
    ]
