# Generated by Django 4.2 on 2024-11-04 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EncounterBulkExport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identifier', models.JSONField(blank=True, null=True)),
                ('period_start', models.CharField(blank=True, null=True)),
                ('period_end', models.CharField(blank=True, null=True)),
                ('hospitalization', models.JSONField(blank=True, null=True)),
                ('subject_reference', models.CharField(blank=True, null=True)),
                ('subject_display', models.CharField(blank=True, null=True)),
                ('appointment', models.JSONField(blank=True, null=True)),
                ('type', models.JSONField(blank=True, null=True)),
                ('meta_last_updated', models.CharField(blank=True, null=True)),
                ('meta_version_id', models.CharField(blank=True, null=True)),
                ('serviceProvider_ref', models.CharField(blank=True, null=True)),
                ('serviceProvider_display', models.CharField(blank=True, null=True)),
                ('location', models.JSONField(blank=True, null=True)),
                ('ref_num', models.CharField(blank=True, null=True)),
                ('reasonCode', models.JSONField(blank=True, null=True)),
                ('text', models.TextField()),
                ('status', models.CharField(blank=True, null=True)),
                ('encounter_class', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicationRequestBulkExport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('extension', models.JSONField(blank=True, null=True)),
                ('substitution', models.JSONField(blank=True, null=True)),
                ('course_of_therapy_type', models.JSONField(blank=True, null=True)),
                ('subject_reference', models.CharField(blank=True, null=True)),
                ('subject_display', models.CharField(blank=True, null=True)),
                ('dispense_request', models.JSONField(blank=True, null=True)),
                ('ref_num', models.CharField(blank=True, null=True)),
                ('text', models.TextField()),
                ('requester_reference', models.CharField(blank=True, null=True)),
                ('requester_display', models.CharField(blank=True, null=True)),
                ('identifier', models.JSONField(blank=True, null=True)),
                ('reported_boolean', models.BooleanField(default=False)),
                ('authored_on', models.CharField(blank=True, null=True)),
                ('medication_codeable_concept', models.JSONField(blank=True, null=True)),
                ('dosage_instruction', models.JSONField(blank=True, null=True)),
                ('meta_last_updated', models.CharField(blank=True, null=True)),
                ('meta_version_id', models.CharField(blank=True, null=True)),
                ('category', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(blank=True, null=True)),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bulk_export.encounterbulkexport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentReferenceBulkExport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.CharField(blank=True, null=True)),
                ('subject_reference', models.CharField(blank=True, null=True)),
                ('subject_display', models.CharField(blank=True, null=True)),
                ('type', models.JSONField(blank=True, null=True)),
                ('content', models.JSONField(blank=True, null=True)),
                ('doc_status', models.CharField(blank=True, null=True)),
                ('context_period_start', models.CharField(blank=True, null=True)),
                ('context_period_end', models.CharField(blank=True, null=True)),
                ('context_reference', models.CharField(blank=True, null=True)),
                ('ref_num', models.CharField(blank=True, null=True)),
                ('text', models.TextField()),
                ('authenticator_reference', models.CharField(blank=True, null=True)),
                ('authenticator_display', models.CharField(blank=True, null=True)),
                ('custodian_reference', models.CharField(blank=True, null=True)),
                ('custodian_display', models.CharField(blank=True, null=True)),
                ('author_reference', models.CharField(blank=True, null=True)),
                ('author_display', models.CharField(blank=True, null=True)),
                ('identifier', models.JSONField(blank=True, null=True)),
                ('category', models.JSONField(blank=True, null=True)),
                ('meta_last_updated', models.CharField(blank=True, null=True)),
                ('meta_version_id', models.CharField(blank=True, null=True)),
                ('status', models.CharField(blank=True, null=True)),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bulk_export.encounterbulkexport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConditionBulkExport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identifier', models.JSONField(blank=True, null=True)),
                ('code', models.JSONField(blank=True, null=True)),
                ('verificationStatus', models.JSONField(blank=True, null=True)),
                ('subject_reference', models.CharField(blank=True, null=True)),
                ('subject_display', models.CharField(blank=True, null=True)),
                ('meta_last_updated', models.CharField(blank=True, null=True)),
                ('meta_version_id', models.CharField(blank=True, null=True)),
                ('ref_num', models.CharField(blank=True, null=True)),
                ('text', models.TextField()),
                ('category', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
