# Generated by Django 4.2 on 2024-11-05 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_export', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conditionbulkexport',
            old_name='verificationStatus',
            new_name='verification_status',
        ),
        migrations.RenameField(
            model_name='encounterbulkexport',
            old_name='reasonCode',
            new_name='reason_code',
        ),
        migrations.RenameField(
            model_name='encounterbulkexport',
            old_name='serviceProvider_display',
            new_name='service_provider_display',
        ),
        migrations.RenameField(
            model_name='encounterbulkexport',
            old_name='serviceProvider_ref',
            new_name='service_provider_ref',
        ),
        migrations.RemoveField(
            model_name='documentreferencebulkexport',
            name='context_reference',
        ),
        migrations.AddField(
            model_name='conditionbulkexport',
            name='encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bulk_export.encounterbulkexport'),
        ),
        migrations.AddField(
            model_name='conditionbulkexport',
            name='encounter_ref',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conditionbulkexport',
            name='extension',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conditionbulkexport',
            name='recorded_date',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentreferencebulkexport',
            name='encounter_ref',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encounterbulkexport',
            name='extension',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicationrequestbulkexport',
            name='encounter_ref',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conditionbulkexport',
            name='text',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentreferencebulkexport',
            name='text',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='encounterbulkexport',
            name='text',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicationrequestbulkexport',
            name='text',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
