# Generated by Django 4.2 on 2024-12-19 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_export', '0002_rename_verificationstatus_conditionbulkexport_verification_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditionbulkexport',
            name='abatement_date_time',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conditionbulkexport',
            name='clinical_status',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conditionbulkexport',
            name='raw_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentreferencebulkexport',
            name='raw_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encounterbulkexport',
            name='account',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encounterbulkexport',
            name='participant',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encounterbulkexport',
            name='priority',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encounterbulkexport',
            name='raw_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicationrequestbulkexport',
            name='intent',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicationrequestbulkexport',
            name='medication_reference',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicationrequestbulkexport',
            name='raw_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicationrequestbulkexport',
            name='reason_code',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicationrequestbulkexport',
            name='recorder',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
